--liquibase formatted sql

--changeset valentinkd3:1
CREATE TABLE IF NOT EXISTS orders(
    id bigint generated by default as identity,
    name varchar(64) NOT NULL,
    price decimal(10,2),
    CONSTRAINT pr_orders_id PRIMARY KEY (id)
);

--changeset valentinkd3:2
CREATE TABLE IF NOT EXISTS users(
    id bigint generated by default as identity PRIMARY KEY,
    username varchar(64) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    role varchar(32) NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);


--changeset valentinkd3:3
CREATE TABLE IF NOT EXISTS basket(
    usr_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT pr_basket_id PRIMARY KEY (usr_id,order_id),
    CONSTRAINT fk_basket_users_id FOREIGN KEY (usr_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_basket_orders_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);